language: node_js
node_js:
- node
script:
- npm run lint -s
deploy:
    provider: heroku
    api_key:
        secure: Lep3AWzlJswDlG56SKTn4nUqZESOcJdTJ4f/NHlg3bjA+l7ckGL145vpopRe0v4x2o2q802CzSGvEf2z4cT2l7OgAxtqTnlZtmBYi0/+pI5Bspp04Zq6rnjhsEWBisVah07RvJZQDXD3G9bEGlLtbxxa1BpU+cUhCzmrC9Wrl83BE6OWgoMg9t61WXyXLITNtnZHcTqLDIrzCus4RCs6wpYXkz8/BdKMyMGa2Us9P5JY3bIyzFIf6firyknp1rPXb6GV6OQOYyCv1KxGaOinVnkz4nXppwJ0i/Ui6JSNF9XmnxFwa1tRVXTk3BQVd0rs/OHQcJ+f7hhaKePOAgYbUdzRQKVYRCsCpPQZEPJI5Mdg9tcX1xe4oOvrUCx7Pz0sL7rSc9PfRKoND2RpgK2Se6ECDHI73Y1xXrybsTPK8eqG9RNK8lji0g7DbXmntkC3EHeLDbr9OgvGm60foDIpW6ZioGTi8DP+UI6H3456ihuC4FrqigjiObsR4Rh0aNGYF4Sww3ISMCfOzkUDRQbINmEpqyX+BTEO29crzZGXE2uWVqrz1sIKa0dKoCMQStYiCL3TsoiIcFD0cvYoqpYPn3PAX/v35CpXYjE9cA1G7JTzqg8im3TYRt/XMDuNSNpAEzjp+j8+5NPsAZr5aQ20wNbSrzpM3zCAw+HjKdGvs6A=
    app: slack-proxy-oauth2
    on:
        repo: antonio-ramadas/slack-proxy-oauth2
